GRANT SELECT, INDEX, REFERENCES ON Buildings TO SORIA, ZAGURI;
GRANT SELECT, INDEX, REFERENCES ON Rooms TO SORIA, ZAGURI;
GRANT SELECT, INDEX, REFERENCES ON EQUIPMENTS TO SORIA, ZAGURI;
GRANT all ON buildings TO SILON;
GRANT all ON Rooms TO SILON;
GRANT all ON room_types TO SILON;
GRANT all ON EQUIPMENTS TO SILON;
